title: Noololly
description: "This is a theme that will be used in the overhaul of Noololly's personal website."
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

enable_dark_theme: true

footer: "(c) 2025 Noololly. MIT license."